### ISSUE TITLE
t-route build failed

### ISSUE THREAD

**Issue by benlee0423** [CIROH-UA/NGIAB-CloudInfra#203]
## Current behavior
t-route build failed with the following error message.
```
#10 202.4 python3: can't open file '/ngen/t-route/src/troute-nwm/setup.py': [Errno 2] No such file or directory
#10 ERROR: process "/bin/sh -c export FC=gfortran NETCDF=/usr/include     && cd ${WORKDIR}/t-route     && ./compiler.sh     && cd ./src/troute-network     && python3 setup.py --use-cython bdist_wheel     && cp dist/*.whl ${WORKDIR}/t-route/wheels/     && cd ../troute-routing     && python3 setup.py --use-cython bdist_wheel     && cp dist/*.whl ${WORKDIR}/t-route/wheels/     && cd ../troute-config     && python3 -m build .     && cp dist/*.whl ${WORKDIR}/t-route/wheels/     && cd ../troute-nwm     && python3 setup.py bdist_wheel     && cp dist/*.whl ${WORKDIR}/t-route/wheels/" did not complete successfully: exit code: 2
```
More detailed error message can be found in recent build
https://github.com/CIROH-UA/NGIAB-CloudInfra/actions/runs/9785757904

## Expected behavior
t-route build successfully.

## Steps to replicate behavior (include URLs)
Initiate build in actions or locally.

**Comment by benlee0423** [comment]
Root cause of this error is due to this commit.
https://github.com/NOAA-OWP/t-route/commit/41b6983dce41e15f41a3a8e24ee5ab38f1fd161b
`src/troute-nwm/setup.py` file removed, and our build use this file.

**Comment by benlee0423** [comment]
The commit [59a6041](https://github.com/NOAA-OWP/t-route/commit/59a604198bb272dbf86f0392c78625ac5402f5ac) on June 12 is the last working commit.

**Comment by benlee0423** [comment]
Getting another error with new build
https://github.com/CIROH-UA/NGIAB-CloudInfra/actions/runs/9802954130

terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  ValidationError: 1 validation error for Config
compute_parameters -> data_assimilation_parameters -> reservoir_da -> reservoir_rfc_da -> reservoir_rfc_forecasts_time_series_path
  file or directory at path "rfc_timeseries" does not exist (type=value_error.path.not_exists; path=rfc_timeseries)

At:
  /usr/local/lib/python3.9/site-packages/pydantic/main.py(341): __init__
  /usr/local/lib/python3.9/site-packages/troute/config/config.py(46): with_strict_mode
  /usr/local/lib/python3.9/site-packages/nwm_routing/input.py(44): _input_handler_v04
  /usr/local/lib/python3.9/site-packages/nwm_routing/__main__.py(56): main_v04


===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 21 RUNNING AT bb573dba80e7
=   EXIT CODE: 134
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Aborted (signal 6)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions

**Comment by benlee0423** [comment]
[issue](https://github.com/NOAA-OWP/t-route/issues/798) filed on the t-route repo.

**Comment by benlee0423** [comment]
https://github.com/NOAA-OWP/t-route/issues/798

**Comment by aaraney** [comment]
The failure you are seeing in CI due to the following line in your `t-route` config:

```yaml
compute_parameters:
  assume_short_ts: true
  compute_kernel: V02-structured
  cpu_pool: 1
  data_assimilation_parameters:
    reservoir_da:
      reservoir_persistence_da:
        reservoir_persistence_usace: false
        reservoir_persistence_usgs: false
      reservoir_rfc_da:
        reservoir_rfc_forecasts: false
        reservoir_rfc_forecasts_lookback_hours: 28
        reservoir_rfc_forecasts_offset_hours: 28
        reservoir_rfc_forecasts_time_series_path: rfc_timeseries/ # <- this is the issue
```

https://github.com/NOAA-OWP/t-route/pull/790 changed `t-route`'s configuration validation behavior. Namely, files and directories that need to exist at runtime are now verified to exist. However, as a user since `reservoir_rfc_forecasts: false` I wouldn't expect that `t-route` would fail since `t-route` won't use the `reservoir_rfc_forecasts_time_series_path` at runtime. Ill open up an issue to track this and see about how we can fix it.
